env:
    # windowやalertも含まれるたくさんのブラウザ用のグローバル変数を一気にglobals設定に登録してしまい、ESLintにチェックしなくてよいと伝える
    browser: true
    # ECMAScript2022を適用
    es2022: true
extends:
    # eslint-plugin-vueが推奨するルールを適用/https://eslint.vuejs.org/user-guide/#installation
    - 'plugin:vue/vue3-recommended'
    - '@vue/typescript/recommended'
    # ESLintが推奨するチェック項目でまとめてチェックする
    - 'eslint:recommended'
parserOptions:
    # env.es2022で指定しているため、ecmaVersionは指定する必要がない
plugins:
    - vue
    - '@typescript-eslint'
rules: { 'vue/html-indent': ['error', 4], 'vue/html-self-closing': ['error', { 'html': { 'void': 'always' } }] }
