env:
    # windowやalertも含まれるたくさんのブラウザ用のグローバル変数を一気にglobals設定に登録してしまい、ESLintにチェックしなくてよいと伝える
    browser: true
    # ECMAScript2021を適用
    es2022: true
extends:
    # eslint-plugin-vueが推奨するルールを適用/https://eslint.vuejs.org/user-guide/#installation
    - 'plugin:vue/vue3-recommended'
    - '@vue/typescript/recommended'
    # ESLintが推奨するチェック項目でまとめてチェックする
    - 'eslint:recommended'
parserOptions:
    # parserOptionsのecmaVersionは、使用するECMAScriptのバージョンを指定します。envのes2021は指定しているため、それに合わせる
    ecmaVersion: 13
plugins:
    - vue
    - '@typescript-eslint'
rules: {}
